### PR TITLE
Switched to CMake build method; moved Boost files into separate folder

### PR DESCRIPTION
**Pull request by ssawchenko**
https://github.com/steamclock/internetmap/issues/447

**Short story:**
New version of Android Studio caused the project to "build symbols" for ~20 mins each time the project was opened / the C files were changed.

**Fix**
* It is recommended that projects move from the old ndk build method, to using CMake. I believe I have managed to convert the .mk file over to a CMakeLists.txr file. While this sped up indexing a little, the project was still seeing ~12 min indexing times.
* Android project is using the C++ Boost library; these header files were in the same folder as the Android-NDK project files and I believe that even though we could not see them in the project, they were still being indexed. I moved these files out to their own folder (Android-Boost), updated the build file and the project builds very quick now with a minimal indexing step.

I would like to push this forward so that moving on I do not have to wait 20 mins each time I open the project, however, I am nervous to change the build method right before shipping.

Your thoughts are appreciated!

### CODE REVIEW

**Comment by nbrooke** [comment]
Seems like a sensible change to me. I share the concern about switching th build process right before shipping, but I THINK that's unnecessary anxiety in this case, the build process does not seem like it's something that would subtly fail 

RE: boost. From a quick look it looks like it's only used to get the shared_ptr class, which is SUPPOSED to be part of the C++ standard library. I assume that was done as a work around for some ancient version of the C++ standard library where that was missing or broken, so I strongly suspect that could be removed now. Not sure if you want to take that on as well at this point though, but maybe once v1 is out the door we should see if we can ditch boost.

**Comment by apike** [comment]
For the record, this PR is blocked on being merged since the APKs it creates don't install on (at least some) supported devices. The buddybuild error was “The selected application variant/abi may not be available for download”

**Comment by ssawchenko** [comment]
Perhaps this is a BuddyBuild issue. The log file for the "successful" build is empty. Maybe there is something different with their NDK setup.

**Comment by ssawchenko** [comment]
Red herring!

Actually this appeared to be a keystore issue, not an NDK issue. I had recently updated BuddyBuild to use the "upload" keystore we have moved to using (allowing us to use the Google key signing method, where they hold onto our private keystore). I had apparently set this up incorrectly. Once I removed the duplicate key I had accidentally uploaded, the APK downloads from BB correctly.

**Comment by ssawchenko** [comment]
Once I am back from vacation let's do a larger test on this branch and merge it in for the next iteration.

**Comment by ssawchenko** [comment]
I have gone through and done another pass through buddy build with these changes and the APK is successfully downloaded and installed on my devices. The changes to the upload keystore appear to have solved the BuddyBuild issue.

**Comment by ssawchenko** [comment]
Confirmed - can upload BB APK (which uses our upload key) to the Google Play store correctly.

**Comment by ssawchenko** [comment]
Merged / squashed manually. Closing PR.

**Pull request closed without merging**
