### PR TITLE
Use UIAlertControllerStyleAlert for UIAlertControllers on iPads #480

### PR DESCRIPTION
**Pull request by ssawchenko**
If running on an iPad, use UIAlertControllerStyleAlert for UIAlertControllers. This will place the popups in the centre of the screen on iPads, and on the bottom of the screen for iPhones (as before).

### CODE REVIEW

**Comment by ssawchenko** [comment]
@apike Seems odd to show these errors on the bottom of the screen even on a phone. Is there a reason this was being done this way?

**Comment by apike** [comment]
Yeah, that is really odd - seems like a conversion error or something? We would only want the bottom-of-screen action sheet when it happens in response to a user action and there are multiple options for them to pick from. Shall we just switch it to using a pop-up alert on both devices?

**Comment by ssawchenko** [comment]
@apike I think moving the errors to be shown as alerts on both phone and tablet makes more sense.

**Comment by apike** [comment]
The code seems reasonable to me - to Abey for testing these network errors on iPad and iPhone.

**Comment by abey** [comment]
Looks good to me 💯

**Comment by ssawchenko** [comment]
Merged with master and fixed up conflict. Once BuddyBuild verifies a successful build I will squash and merge.

**Pull request merged**
