### PR TITLE
iPhone X UI updates #484

### PR DESCRIPTION
**Pull request by ssawchenko**
* Updated UIViewControllers to adhere to the new iOS 11 safe area
* Menu items now equally spaced across top on phones
* CreditsViewController now shows status bar
* CreditsViewController now has rounded close button

Note, one or two tricky issues remain #495. I have moved them into a separate issue and may ask for help on them as they involve some older 3rd party pods that may need to get updated.

Assigning to @abey for QA verification

### CODE REVIEW

**Comment by apike** [comment]
I did a testing round since I have the X currently - looks good to me! :+1:

**Comment by abey** [comment]
Everything works well for me except the loading image that you see instead of the search icon when "Your Location" is clicked. 
loading image

This is how it looks in action. This issue is present in other iPhones too when running this build. 
delete me

Other than this small issue everything else works great 🚀

**Comment by apike** [comment]
Okay cool, let's get this merged @ssawchenko and we'll fix that spinner placement in the other tweaks issue.

**Comment by ssawchenko** [comment]
Merged in @nbrooke's changes for #498. 
Will leave this PR open until next week where I will fix up the location of the spinner icons.

**Comment by ssawchenko** [comment]
@apike @abey I have centred the spinning load icons, please let me know if that is sufficient.

**Comment by abey** [comment]
Looks good for me 👍

**Comment by apike** [comment]
Cool, let's get this merged and then we can do a test pass on master before releasing.

**Pull request merged**
