### PR TITLE
Show new contact page for "managed IT services", and put "open source" in modal

### PR DESCRIPTION
**Pull request by jotkali**
issue #418 

(ignore branch name)

### CODE REVIEW

**Comment by apike** [comment]
:+1:

**Comment by apike** [comment]
@jotkali Once you get a thumbs up and a PR is assigned back to you, you can merge it (or if you'd rather me merge your PRs once I give a thumbs up let me know and I can do that instead.)

**Comment by apike** [comment]
Or is this PR superseded by #421?

**Comment by jotkali** [comment]
Yes this was more of a hot fix per your request.

**Pull request closed without merging**
