### PR TITLE
limiting pan and tilt, and zoom

### LINKED ISSUE #394: Change globe camera so that south is always down
Right now you can use two fingers to rotate the globe into a hard-to-recognize sideways or upside-down orientation. Let's change the globe-mode camera controls to let you pan and zoom but keep south always down.

### LINKED ISSUE #396: Change globe node selection so camera always points in with south down
Once we've made south point down in the typical case in #394, we should improve the orientation for node selection in globe view.

Right now when a node is selected, it naively zooms the camera to be close to the node from the current location. Instead, we should zoom to a point *outside* the globe pointing at the desired node, with south facing down.

### PR DESCRIPTION
**Pull request by jotkali**
Limiting 2 finger rotation side to side, and tilt forth and back, so user will be less confused with state of globe. 

Limited zoom so user can not go "into" the globe. user can still select a node not facing the user and end up inside the node.

fixes #396 
fixes #394

### CODE REVIEW

**Comment by apike** [comment]
@jotkali Did you mean to close this PR?

**Comment by apike** [comment]
Some notes on this build:
- The maximum zoom is way too far out - you can't make out specific nodes on the globe view. If we want to work on zoom limitations we can do that as a separate PR.
- The camera restrictions should only apply in Globe view - they don't improve anything in Network view and just feel weird there
- I would have sworn the build yesterday didn't allow side-to-side tilting the globe, but this does but only to a limited tilt. I'm inclined to say the preferable behaviour would be no side-to-side tilting at all, but if @jotkali and @ssawchenko both prefer the side-to-side tilting but limited to an angle, I could be convinced.
- This breaks the Android build so we'll need to get that resolved before merging.

**Comment by apike** [comment]
Also, when you press the Info button, it turns the globe sideways 😆

**Comment by ssawchenko** [comment]
@apike Yesterday I believe there was no side-to-side tilting. We were both working on our own versions of the code, so I'll check and see if there are differences in our methods.

Android is busted because there are some string methods that for some terrible reason are not available to us. Removing the test code we have in there to print out the matrix will hopefully fix this issue.

**Comment by jotkali** [comment]
pushed info menu fix (bad test code left in), and set zoom back to original.

Shayla is looking at network vs globe view

**Comment by ssawchenko** [comment]
@nbrooke Please have a look at these last few commits.

To allow us to support the new fixed rotation restrictions on both portrait and landscape orientations, I have added in two methods on the Camera class:

1. **setMode**: allows us to set Globe or Network modes for the camera, which is how we determine if the rotations need to be locked or not. I am not 100% happy with the naming here, but I figure it was slightly easier to apply the logic here than to try and move it to the visualization classes.

2. **setOrientation**: set the orientation so we know if we should apply the final rotation on phones.

*TODO* Figure out why polarToCartesian is acting funny for the lat/lng lines

**Comment by apike** [comment]
New issue I just noticed (not sure if it was there last time I tested this PR: you can no longer tap on nodes to select them.

**Comment by ssawchenko** [comment]
Bah. They were working earlier today... perhaps something is even more messed up with the orientation changes than I originally thought. 

I may have to revert these past few commits and see if @nbrooke can come up with a better solution.

**Comment by nbrooke** [comment]
Above build should fix the orientation issues in a cleaner way, and the node selection does seem to work properly now.

**Comment by apike** [comment]
This is working for me now on iPhone and iPad. :star:. @ssawchenko can you do a pass on getting this PR to build on Android so we can merge it?

**Comment by ssawchenko** [comment]
@apike Fixed up the issues in Android, tested on both landscape and portrait orientations - everything seems ok. Zooming, rotating and node selections appear to function as expected.

I will continue to test on other devices, but for now I'd say this is good to merge/squash.

**Comment by ssawchenko** [comment]
@nbrooke Removed the old GlobeVisualization::setPortrait call. Unclear why the app was still building.

**Comment by apike** [comment]
:+1: Let's merge!

**Pull request merged**
